In [1]:
import requests
import numpy as np
import base64

In [2]:
biencoder = 'http://localhost:30300/api/blink/biencoder/mention'

In [3]:
"I would like to see"

'I would like to see'

In [3]:
samples = [
    {
        "label": "unknown",
        "label_id": -1,
        "context_left": "I would like to see",
        "context_right": "by night.",
        "mention": "Milan",
        "start_pos": 0,
        "end_pos": 0,
        "sent_idx": 0
    },
    {
        "label": "unknown",
        "label_id": -1,
        "context_left": "I would like to see",
        "context_right": "playing.",
        "mention": "Milan",
        "start_pos": 0,
        "end_pos": 0,
        "sent_idx": 0
    },
    {
        "label": "unknown",
        "label_id": -1,
        "context_left": "I would like to see",
        "context_right": "playing by night.",
        "mention": "Milan",
        "start_pos": 0,
        "end_pos": 0,
        "sent_idx": 0
    },
    {
        "label": "unknown",
        "label_id": -1,
        "context_left": "I would like to see",
        "context_right": "playing in the night.",
        "mention": "Milan",
        "start_pos": 0,
        "end_pos": 0,
        "sent_idx": 0
    },
    {
        "label": "unknown",
        "label_id": -1,
        "context_left": "I would like to see",
        "context_right": "by night playing.",
        "mention": "Milan",
        "start_pos": 0,
        "end_pos": 0,
        "sent_idx": 0
    },
    {
        "label": "unknown",
        "label_id": -1,
        "context_left": "My name is ",
        "context_right": " and I work in Milan.",
        "mention": "Riccardo Pozzi",
        "start_pos": 0,
        "end_pos": 0,
        "sent_idx": 0
    },
]

In [4]:
res = requests.post(biencoder, json=samples)

In [5]:
res.ok

True

In [6]:
res = res.json()

In [7]:
len(res['encodings'])

6

In [10]:
def vector_decode(s, dtype=np.float32):
    buffer = base64.b64decode(s)
    v = np.frombuffer(buffer, dtype=dtype)
    return v

In [11]:
[vector_decode(e) for e in res['encodings']]

[array([ 0.12820284,  0.08571127,  0.06788564, ..., -0.04339211,
        -0.11725296,  0.00919822], dtype=float32),
 array([ 0.12246934, -0.09969883,  0.0544334 , ..., -0.0339468 ,
        -0.10125329, -0.07698297], dtype=float32),
 array([ 0.13450775, -0.06332049,  0.03040912, ..., -0.03297743,
        -0.07788822, -0.08407027], dtype=float32),
 array([ 0.12821673, -0.09233658,  0.05173017, ..., -0.0126435 ,
        -0.07907206, -0.08979845], dtype=float32),
 array([ 0.1253362 , -0.03025142,  0.00893456, ..., -0.03998447,
        -0.08499372, -0.0769273 ], dtype=float32),
 array([ 0.08870525, -0.11915075, -0.00045362, ...,  0.10456717,
         0.02674502, -0.08438934], dtype=float32)]

In [12]:
indexer = 'http://localhost:30301/api/indexer/search'

In [13]:
body = {
    'encodings': res['encodings'],
    'top_k': 10
}

In [14]:
res_indexer = requests.post(indexer, json=body)

In [15]:
res_indexer.ok

True

In [17]:
res_indexer.json()

[[{'raw_score': 325.5143737792969,
   'id': 18523,
   'title': 'Milan',
   'url': 'https://en.wikipedia.org/wiki?curid=36511',
   'indexer': 0,
   'score': 81.8663101196289},
  {'raw_score': 333.94805908203125,
   'id': 2344102,
   'title': 'A.C. Milan',
   'url': 'https://en.wikipedia.org/wiki?curid=18940588',
   'indexer': 0,
   'score': 77.64945983886719},
  {'raw_score': 334.37457275390625,
   'id': 130771,
   'title': 'Milan (disambiguation)',
   'url': 'https://en.wikipedia.org/wiki?curid=268122',
   'indexer': 0,
   'score': 77.43624877929688},
  {'raw_score': 334.7796325683594,
   'id': 22593,
   'title': 'Lombardy',
   'url': 'https://en.wikipedia.org/wiki?curid=43807',
   'indexer': 0,
   'score': 77.23369598388672},
  {'raw_score': 334.9159240722656,
   'id': 30585,
   'title': 'Como',
   'url': 'https://en.wikipedia.org/wiki?curid=60679',
   'indexer': 0,
   'score': 77.16557312011719},
  {'raw_score': 335.0386962890625,
   'id': 9362,
   'title': 'Mumbai',
   'url': 'https

In [18]:
candidates = res_indexer.json()
candidates

[[{'raw_score': 325.5143737792969,
   'id': 18523,
   'title': 'Milan',
   'url': 'https://en.wikipedia.org/wiki?curid=36511',
   'indexer': 0,
   'score': 81.8663101196289},
  {'raw_score': 333.94805908203125,
   'id': 2344102,
   'title': 'A.C. Milan',
   'url': 'https://en.wikipedia.org/wiki?curid=18940588',
   'indexer': 0,
   'score': 77.64945983886719},
  {'raw_score': 334.37457275390625,
   'id': 130771,
   'title': 'Milan (disambiguation)',
   'url': 'https://en.wikipedia.org/wiki?curid=268122',
   'indexer': 0,
   'score': 77.43624877929688},
  {'raw_score': 334.7796325683594,
   'id': 22593,
   'title': 'Lombardy',
   'url': 'https://en.wikipedia.org/wiki?curid=43807',
   'indexer': 0,
   'score': 77.23369598388672},
  {'raw_score': 334.9159240722656,
   'id': 30585,
   'title': 'Como',
   'url': 'https://en.wikipedia.org/wiki?curid=60679',
   'indexer': 0,
   'score': 77.16557312011719},
  {'raw_score': 335.0386962890625,
   'id': 9362,
   'title': 'Mumbai',
   'url': 'https

In [19]:
[len(c) for c in candidates]

[10, 10, 10, 10, 10, 10]

In [20]:
[c[0] for c in candidates]

[{'raw_score': 325.5143737792969,
  'id': 18523,
  'title': 'Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=36511',
  'indexer': 0,
  'score': 81.8663101196289},
 {'raw_score': 323.9443054199219,
  'id': 2344102,
  'title': 'A.C. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=18940588',
  'indexer': 0,
  'score': 83.17942810058594},
 {'raw_score': 324.51580810546875,
  'id': 2344102,
  'title': 'A.C. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=18940588',
  'indexer': 0,
  'score': 82.65389251708984},
 {'raw_score': 324.27642822265625,
  'id': 2344102,
  'title': 'A.C. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=18940588',
  'indexer': 0,
  'score': 83.0195083618164},
 {'raw_score': 325.9125671386719,
  'id': 2344102,
  'title': 'A.C. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=18940588',
  'indexer': 0,
  'score': 81.61531066894531},
 {'raw_score': 334.0375671386719,
  'id': 4679300,
  'title': 'Riccardo Pozzo',
  'url': 'https://en.wikipedia

In [21]:
crossencoder = 'http://localhost:30302/api/blink/crossencoder'

In [22]:
body = {
    'samples': samples,
    'candidates': candidates
}

In [23]:
res = requests.post(crossencoder, json=body)

In [24]:
res.ok

True

In [25]:
cross_candidates = res.json()
cross_candidates

[[{'id': 18523,
   'title': 'Milan',
   'url': 'https://en.wikipedia.org/wiki?curid=36511',
   'indexer': 0,
   'score': 9.614951133728027,
   'bi_score': 81.8663101196289},
  {'id': 2344102,
   'title': 'A.C. Milan',
   'url': 'https://en.wikipedia.org/wiki?curid=18940588',
   'indexer': 0,
   'score': 1.3588080406188965,
   'bi_score': 77.64945983886719},
  {'id': 22593,
   'title': 'Lombardy',
   'url': 'https://en.wikipedia.org/wiki?curid=43807',
   'indexer': 0,
   'score': -3.2848315238952637,
   'bi_score': 77.23369598388672},
  {'id': 9362,
   'title': 'Mumbai',
   'url': 'https://en.wikipedia.org/wiki?curid=19189',
   'indexer': 0,
   'score': -4.8576765060424805,
   'bi_score': 77.10418701171875},
  {'id': 2799,
   'title': 'Cologne',
   'url': 'https://en.wikipedia.org/wiki?curid=6187',
   'indexer': 0,
   'score': -6.372450351715088,
   'bi_score': 76.4428939819336},
  {'id': 23108,
   'title': 'Bari',
   'url': 'https://en.wikipedia.org/wiki?curid=44784',
   'indexer': 0,


In [26]:
[len(c) for c in cross_candidates]

[10, 10, 10, 10, 10, 10]

In [27]:
[c[0] for c in cross_candidates]

[{'id': 18523,
  'title': 'Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=36511',
  'indexer': 0,
  'score': 9.614951133728027,
  'bi_score': 81.8663101196289},
 {'id': 2344102,
  'title': 'A.C. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=18940588',
  'indexer': 0,
  'score': 9.359381675720215,
  'bi_score': 83.17942810058594},
 {'id': 2344102,
  'title': 'A.C. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=18940588',
  'indexer': 0,
  'score': 9.224342346191406,
  'bi_score': 82.65389251708984},
 {'id': 2344102,
  'title': 'A.C. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=18940588',
  'indexer': 0,
  'score': 9.521745681762695,
  'bi_score': 83.0195083618164},
 {'id': 2344102,
  'title': 'A.C. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=18940588',
  'indexer': 0,
  'score': 7.249083042144775,
  'bi_score': 81.61531066894531},
 {'id': 4679300,
  'title': 'Riccardo Pozzo',
  'url': 'https://en.wikipedia.org/wiki?curid=44960334',
  'indexer': 0

In [28]:
samples[2]

{'label': 'unknown',
 'label_id': -1,
 'context_left': 'I would like to see',
 'context_right': 'playing by night.',
 'mention': 'Milan',
 'start_pos': 0,
 'end_pos': 0,
 'sent_idx': 0}

In [29]:
cross_candidates

[[{'id': 18523,
   'title': 'Milan',
   'url': 'https://en.wikipedia.org/wiki?curid=36511',
   'indexer': 0,
   'score': 9.614951133728027,
   'bi_score': 81.8663101196289},
  {'id': 2344102,
   'title': 'A.C. Milan',
   'url': 'https://en.wikipedia.org/wiki?curid=18940588',
   'indexer': 0,
   'score': 1.3588080406188965,
   'bi_score': 77.64945983886719},
  {'id': 22593,
   'title': 'Lombardy',
   'url': 'https://en.wikipedia.org/wiki?curid=43807',
   'indexer': 0,
   'score': -3.2848315238952637,
   'bi_score': 77.23369598388672},
  {'id': 9362,
   'title': 'Mumbai',
   'url': 'https://en.wikipedia.org/wiki?curid=19189',
   'indexer': 0,
   'score': -4.8576765060424805,
   'bi_score': 77.10418701171875},
  {'id': 2799,
   'title': 'Cologne',
   'url': 'https://en.wikipedia.org/wiki?curid=6187',
   'indexer': 0,
   'score': -6.372450351715088,
   'bi_score': 76.4428939819336},
  {'id': 23108,
   'title': 'Bari',
   'url': 'https://en.wikipedia.org/wiki?curid=44784',
   'indexer': 0,


In [30]:
cross_candidates[2]

[{'id': 2344102,
  'title': 'A.C. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=18940588',
  'indexer': 0,
  'score': 9.224342346191406,
  'bi_score': 82.65389251708984},
 {'id': 18523,
  'title': 'Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=36511',
  'indexer': 0,
  'score': 1.7046360969543457,
  'bi_score': 80.57861328125},
 {'id': 7251,
  'title': 'Inter Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=15116',
  'indexer': 0,
  'score': -0.6689072847366333,
  'bi_score': 80.10856628417969},
 {'id': 3749634,
  'title': 'A.C.F. Milan',
  'url': 'https://en.wikipedia.org/wiki?curid=34604048',
  'indexer': 0,
  'score': -5.378426551818848,
  'bi_score': 79.2598648071289},
 {'id': 5611668,
  'title': '2018–19 A.C. Milan season',
  'url': 'https://en.wikipedia.org/wiki?curid=57327712',
  'indexer': 0,
  'score': -6.517227649688721,
  'bi_score': 78.76331329345703},
 {'id': 3852853,
  'title': '2012–13 A.C. Milan season',
  'url': 'https://en.wikipedia.org/wiki?curid

In [33]:
topent = []
for c, sam in zip(cross_candidates, samples):
    topent.append({
        'max_bi': c[0]['bi_score'],
        'max_cross': c[0]['score'],
        'mention': sam['mention'],
        'title': c[0]['title']
    })

In [34]:
topent

[{'max_bi': 81.8663101196289,
  'max_cross': 9.614951133728027,
  'mention': 'Milan',
  'title': 'Milan'},
 {'max_bi': 83.17942810058594,
  'max_cross': 9.359381675720215,
  'mention': 'Milan',
  'title': 'A.C. Milan'},
 {'max_bi': 82.65389251708984,
  'max_cross': 9.224342346191406,
  'mention': 'Milan',
  'title': 'A.C. Milan'},
 {'max_bi': 83.0195083618164,
  'max_cross': 9.521745681762695,
  'mention': 'Milan',
  'title': 'A.C. Milan'},
 {'max_bi': 81.61531066894531,
  'max_cross': 7.249083042144775,
  'mention': 'Milan',
  'title': 'A.C. Milan'},
 {'max_bi': 81.51480102539062,
  'max_cross': 2.771686315536499,
  'mention': 'Riccardo Pozzi',
  'title': 'Riccardo Pozzo'}]

In [35]:
nilpredictor = 'http://localhost:30303/api/nilprediction'

In [36]:
nilres = requests.post(nilpredictor, json=topent)

In [37]:
nilres

<Response [200]>

In [38]:
nilres.json()

{'nil_score_bi': [0.6768686578555411,
  0.5165266640580761,
  0.5030287227567096,
  0.5124209046743384,
  0.4763594659618202,
  0.40748286828895747],
 'nil_score_cross': [0.7955729005469351,
  0.7431998106058398,
  0.7424230702374012,
  0.7518378941584062,
  0.6583247449235026,
  0.3941425501217192]}